format = """\
[î‚¶](fg:#2C2B3C)\
$username\
[î‚´](fg:#2C2B3C bg:#313041)\
$directory\
[î‚´](fg:#313041 bg:#353446)\
$git_branch\
$git_status\
[î‚´](fg:#353446 bg:#3E3D4F)\
$all\
$cmd_duration\
$jobs\
$battery\
$time\
$character"""
# [î‚´](fg:#3E3D4F bg:#333a56)\

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "fg:#CFB3E5 bg:#2C2B3C"
style_root = "fg:#CFB3E5 bg:#2C2B3C"
format = '[îŠ† ]($style)' # $user

[directory]
style = "fg:#E5B9C6 bg:#313041"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = "ï€• ~"
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ğŸœ "
"Pictures" = "ï‘† "
"Videos" = "ï€½ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_branch]
symbol = "ï˜"
style = "fg:#a6e3a1 bg:#353446"
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = "fg:#a6e3a1 bg:#353446"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"
format = '[$all_status$ahead_behind ]($style)'


[aws]
symbol = "îŒ½ "
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[conda]
symbol = "ï„Œ"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[dart]
symbol = "î˜"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[c]
symbol = "î˜"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol $context]($style) $path '

[elixir]
symbol = "î‰µ"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[elm]
symbol = "î˜¬"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[golang]
symbol = "ï³‘"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[haskell]
symbol = "Î»"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[java]
symbol = "î‰–"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[julia]
symbol = "î˜¤"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[lua]
symbol = "î˜ "
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[nim]
symbol = "ïš¤"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[nix_shell]
symbol = "ï‹œ"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[nodejs]
symbol = "î‰"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[perl]
symbol = "î©"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[php]
symbol = "î˜ˆ"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[python]
symbol = "î˜†"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[ruby]
symbol = "îˆ¾"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[rust]
symbol = "ğŸ¦€"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[swift]
symbol = "ï¯£"
style = "fg:#cba6f7 bg:#3E3D4F"
format = '[ $symbol ($version )]($style)'

[package]
symbol = "ï£–"
style = "fg:#cba6f7 bg:#3E3D4F"
format = "[ $symbol $version]($style)"
disabled = true


[cmd_duration]
min_time = 1
style = "fg:#f9e2af bg:#333a56"
format = "[ $duration]($style)"
disabled = true

[jobs]
symbol = "ïª´"
style = "fg:#f9e2af bg:#333a56"
format = "[ $symbol]($style)"

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "
unknown_symbol = "ï•¼ "
empty_symbol = "ï– "
format = "[ $symbol$percentage ]($style bg:#333a56)"
disabled = true

[[battery.display]]
threshold = 15
style = "bold fg:#CFB3E5"

[[battery.display]]
threshold = 50
style = "fg:#f9e2af"

[[battery.display]]
threshold = 101
style = "bold #a6e3a1"

# Prompt: optional param 1
[time]
disabled = true
time_format = "%R"
style = "bg:#3b4363"
format = '[î‚´](fg:#333a56 $style)[ ï•ª $time ](fg:#94e2d5 $style)'

# Last param in the first line/row
# fg:#3b4363 if time enabled
[character]
success_symbol = "[îƒ€ ](fg:#3E3D4F)"
error_symbol = "[îƒ† ](fg:#3E3D4F)"
