import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]
live_config_reload = true


[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 30
y = 30
